---
- name: Create .apps directory in home
  file:
    path: ~/.apps
    state: directory

- name: Add the flathub flatpak repository remote
  command: flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install flatpak apps
  become: no
  flatpak: name={{item.pkg}}
  loop: "{{flatpak_apps}}"

- name: Create flatpak links in .apps
  become: no
  template:
    src: ../templates/flat_app.j2
    dest: ~/.apps/{{item.name}}
    mode: u+x
  loop: "{{flatpak_apps}}"

- name: Copy custom apps
  copy:
    src: "{{item}}"
    dest: ~/.apps
    mode: u+x
  with_items:
    - ../files/nightmode
    - ../files/reset_nightmode