---
- name: Install fedora workstation repos
  become: yes
  dnf:
    name: fedora-workstation-repositories

- name: Install google-chrome
  become: yes
  dnf:
    enablerepo: google-chrome
    name: google-chrome-stable
