---
- name: Install common packages
  become: yes
  dnf:
    name:
    - make
    - autoconf
    - automake
    - nano
    - git-lfs
    - git-crypt

- name: Install utilities
  become: yes
  dnf:
    name:
    - network-manager-applet
    - arandr
    - redshift
    - pavucontrol
