---
- name: Install common packages
  become: yes
  dnf:
    name:
    - make
    - autoconf
    - automake
    - nano
    - git-lfs
    - git-crypt
    - dnf-automatic

- name: Install utilities
  become: yes
  dnf:
    name:
    - network-manager-applet
    - arandr
    - redshift
    - pavucontrol
    - podman
    - toolbox

- name: Activate auto updates
  become: yes
  service:
    name: dnf-automatic.timer
    enabled: yes
