---
- name: Install golang
  become: yes
  dnf:
    name: golang

- name: Install command line tools
  become: yes
  dnf:
    name:
    - redis
    - protobuf-compiler

- name: Install golang packages
  become: no
  shell: go get github.com/golang/protobuf/protoc-gen-go

- name: Add k8s repo
  become: yes
  yum_repository:
    name: kubernetes
    description: Kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Install kubectl
  become: yes
  dnf:
    name: kubectl

- name: Add bazel repo
  become: yes
  command:
    cmd: "dnf copr enable -y vbatts/bazel"
    creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:vbatts:bazel.repo

- name: Install bazel
  become: yes
  dnf:
    name: bazel
