---
- name: Install golang
  become: yes
  dnf:
    name: golang

- name: Install command line tools
  become: yes
  dnf:
    name:
    - redis
    - protobuf-compiler

- name: Install golang packages
  become: no
  shell: go get github.com/golang/protobuf/protoc-gen-go