---
- name: Install common packages
  become: yes
  dnf:
    name:
    - make
    - autoconf
    - automake
    - nano

- name: Install utilities
  become: yes
  dnf:
    name:
    - network-manager-applet
    - arandr
    - redshift
    - pavucontrol
